# Generated by Django 5.1.3 on 2024-11-30 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import datetime


def set_default_submitted_date(apps, schema_editor):
    Author = apps.get_model('my_app', 'Author')
    Book = apps.get_model('my_app', 'Book')
    Novel = apps.get_model('my_app', 'Novel')
    Reader = apps.get_model('my_app', 'Reader')
    Review = apps.get_model('my_app', 'Review')
    for author in Author.objects.all():
        author.submitted_date = datetime.date(2000, 1, 1)  # Set your desired default date
        author.save()
    for book in Book.objects.all():
        book.submitted_date = datetime.date(2000, 1, 1)
        book.save()
    for novel in Novel.objects.all():
        novel.submitted_date = datetime.date(2000, 1, 1)
        novel.save()
    for reader in Reader.objects.all():
        reader.signup_date = datetime.date(2000, 1, 1)
        reader.save()
    for review in Review.objects.all():
        review.review_date = datetime.date(2000, 1, 1)
        review.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                # Add the submitted_date field
                ('submitted_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('published_date', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.author')),
            ],
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('published_date', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.author')),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_books', models.ManyToManyField(related_name='favorite_readers', to='my_app.book')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reader_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.book')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.reader')),
            ],
        ),
        # Populate existing rows with a default submitted_date
        migrations.RunPython(set_default_submitted_date),
        # Make submitted_date non-nullable
        migrations.AlterField(
            model_name='author',
            name='submitted_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]

