# Generated by Django 5.1.4 on 2024-12-26 19:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedbackquestion",
            name="category",
        ),
        migrations.AddField(
            model_name="manuscript",
            name="beta_readers_needed",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="budget",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="cover_art",
            field=models.FileField(
                blank=True, null=True, upload_to="uploads/cover_art/% Y/% m/% d/"
            ),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="nda_file",
            field=models.FileField(
                blank=True, null=True, upload_to="uploads/nda/% Y/% m/% d/"
            ),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="plot_summary",
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="feedbackquestion",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Is this question active and selectable?"
            ),
        ),
        migrations.AlterField(
            model_name="manuscript",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, help_text="Timestamp of creation"
            ),
        ),
        migrations.AlterField(
            model_name="manuscript",
            name="file_path",
            field=models.FileField(upload_to="uploads/manuscript/% Y/% m/% d/"),
        ),
        migrations.AlterField(
            model_name="manuscript",
            name="nda_required",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="manuscript",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("in_review", "In Review"),
                    ("completed", "Completed"),
                ],
                default="draft",
                help_text="Status of the manuscript",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="manuscript",
            name="updated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, help_text="Timestamp of last update"
            ),
        ),
    ]
