# Generated by Django 5.1.4 on 2025-02-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(
                max_length=20,
                choices=[("author", "Author"), ("beta_reader", "Beta Reader"), ("admin", "Admin")],
                default="author",  # Avoid NULL issues
            ),
        ),
    ]
