# Generated by Django 5.1.4 on 2024-12-28 02:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field1", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "my_table_name",
            },
        ),
    ]
