# Generated by Django 5.1.4 on 2025-01-20 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="betareader",
            name="genres",
        ),
        migrations.RemoveField(
            model_name="betareader",
            name="user",
        ),
        migrations.AddField(
            model_name="betareader",
            name="keywords",
            field=models.ManyToManyField(
                blank=True,
                help_text="Keywords the beta reader is interested in",
                related_name="beta_readers",
                to="my_app.keyword",
            ),
        ),
        migrations.AddField(
            model_name="betareader",
            name="profile",
            field=models.OneToOneField(
                default=1,
                help_text="The profile associated with this beta reader",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="beta_reader_profile",
                to="my_app.profile",
            ),
        ),
        migrations.AddField(
            model_name="betareader",
            name="rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Average rating for this beta reader",
                max_digits=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="betareader",
            name="total_reviews",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Total number of reviews completed by the beta reader",
            ),
        ),
        migrations.DeleteModel(
            name="Genre",
        ),
    ]
