# Generated by Django 5.1.4 on 2025-01-13 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReaderManuscript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="in_progress",
                        max_length=50,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "manuscript",
                    models.ForeignKey(
                        help_text="The manuscript chosen by the reader",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readers",
                        to="my_app.manuscript",
                    ),
                ),
                (
                    "reader",
                    models.ForeignKey(
                        help_text="The reader associated with the manuscript",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reader_manuscripts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
