# Generated by Django 5.1.4 on 2025-02-13 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0002_fix_role_column"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("author", "Author"),
                    ("beta_reader", "Beta Reader"),
                    ("admin", "Admin"),
                ],
                help_text="Role of the user",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                help_text="User who owns the profile",
                on_delete=django.db.models.deletion.CASCADE,
                to="my_app.customuser",
            ),
        ),
    ]
