# Generated by Django 5.1.3 on 2024-12-02 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_rename_submitted_date_author_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authorbook',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='authorbook',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='booknovel',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='booknovel',
            old_name='novel_id',
            new_name='novel',
        ),
        migrations.RenameField(
            model_name='readernovel',
            old_name='novel_id',
            new_name='novel',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='reader_id',
            new_name='reader',
        ),
        migrations.RemoveField(
            model_name='author',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='novel',
            name='novel_id',
        ),
        migrations.RemoveField(
            model_name='reader',
            name='reader_id',
        ),
        migrations.RemoveField(
            model_name='readernovel',
            name='user_id',
        ),
        migrations.AddField(
            model_name='readernovel',
            name='reader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_app.reader'),
        ),
        migrations.AlterField(
            model_name='author',
            name='date',
            field=models.DateField(default='2023-01-01'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
