# Generated by Django 5.1.3 on 2024-12-02 18:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_rename_author_id_authorbook_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='user_signup_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
