# Generated by Django 5.1.4 on 2025-01-20 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0003_alter_betareader_profile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="manuscript",
            options={
                "permissions": [
                    ("can_view_reader_dashboard", "Can view reader dashboard"),
                    ("can_view_author_dashboard", "Can view author dashboard"),
                ]
            },
        ),
    ]
