# Generated by Django 5.1.4 on 2025-02-14 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0003_alter_profile_user"),
    ]

    operations = []
