# Generated by Django 5.1.4 on 2025-01-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0004_alter_manuscript_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("author", "Author"),
                    ("beta_reader", "Beta Reader"),
                    ("admin", "Admin"),
                ],
                help_text="Role of the user",
                max_length=20,
            ),
        ),
    ]
