# Generated by Django 5.1.4 on 2024-12-21 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0004_manuscriptkeywords"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BetaReader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "experience",
                    models.TextField(
                        blank=True,
                        help_text="Summary of the beta reader's experience",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the beta reader profile was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When the beta reader profile was last updated",
                    ),
                ),
                (
                    "genres",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Genres the beta reader is interested in",
                        related_name="beta_readers",
                        to="my_app.genre",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="The user who is a beta reader",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beta_reader_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
