# Generated by Django 5.1.4 on 2024-12-22 17:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_app", "0005_betareader"),
    ]

    operations = [
        # migrations.AddField(
        # model_name="manuscript",
        # name="created_at",
        # field=models.DateTimeField(
        # auto_now_add=True, default=django.utils.timezone.now
        # ),
        # preserve_default=False,
        # ),
    ]
